BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/D7hdCMvZQS7MscTghzr71A/348s.jpg','Rhinegeist Brewery', 'Brewing hoppy & sessionable craft beer and investing in the character of the Over the Rhine and greater brewing communities.', 'Brewery', '1910 Elm St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.5', '(513) 381-1356');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/tolQEd7e6F1bQmRXtYF_LQ/348s.jpg', 'Taft''s Ale House', '10+ brewed in house craft beers on tap, Tri-Tip Steak, Salads, Chicken, Salmon, all in the setting of a renovated old church that was built in 1850.', 'Brewery', '1429 Race St', 'Cincinnati', 'OH', '45202','11:00:00', '23:00:00', '4.5', '(513) 334-1393');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/crZJ8YPlUdckqj_el2HBUA/348s.jpg', 'BrewDog Cincinnati', 'Two hours south of our American HQ we opened an 8,500 sq ft craft beer mecca! With 24 taps of craft beer glory, a mezzanine chock full of games, and a beer school space for everything beer geekery, BrewDog Cincinnati is THE place to experience craft beer in The Queen City. We are also dog friendly in our outside areas, so you can bring your furry friend with you!', 'Brewery', '316 Reading Rd', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.0', '(513) 457-5287');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/X8PZHucus9wI6gP9ePwtQQ/348s.jpg', 'Braxting Brewing Cincinnati', 'Braxton Brewing Company melds the 500 year-old tradition of making beer with new age consumer technology. Located in Greater Cincinnati our Taproom of the Future will be a showcase to our craft beers, and redefine the beer drinking experience. We are creating the brewery of your dreams in the heart of the new Midwest, and cannot wait to pour you a pint!', 'Brewery', '331 E 13th St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.0', '(859) 261-5600');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/mKcWr3vj3_DexLBF6NXvuQ/348s.jpg','Samuel Adams Cincinnati Taproom', 'Located in the Over-The Rhine neighborhood, just a block away from historic Findlay Market, our Cincinnati Taproom features pints and flights of our innovative styles, rotating experimental beers, as well as fan-favorites like Samuel Adams Boston Lager, and seasonal brews like Samuel Adams Summer Ale.', 'Brewery', '1727 Logan St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.5', '(513) 412-3300');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/o5tVsT5Ye1OestY-we0OVQ/348s.jpg', 'Condado Tacos', 'We are all about the tacos, tequila + margaritas here at Condado Cincinnati Banks, but the main attraction is our build-your-own tacos! Choices range from toppings + proteins, to shells + sauces. We pride ourselves on having fresh ingredients made every single day and -- unlike other joints -- tacos made your way.', 'Mexican', '195 E Freedom Way', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.0', '(513) 263-1172');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/IAFd8m5KYNoxY-y7Xh9TCw/348s.jpg','Bakersfield', 'Serving up authentic, Mexican street fare, and a selection of over 100 tequilas and American whiskeys. Bakersfield is a spot where the food is simple, the service is warm and the atmosphere is alive.', 'Mexican', '1213 Vine St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.5', '(513) 579-0446');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://www.gomezsalsa.com/wp-content/uploads/2019/04/Location_OTR.jpg', 'Gomez Salsa', 'Gomez Salsa began in the small town of Brownsville, Texas where the best taco of my life was assembled by my abuelita (grandmother), Oralia Gomez. She also hand-chopped the most authentic salsa I’ve ever encountered, which my father made weekly for our family. From them, I learned to make salsa the way they did and began producing and selling Gomez Salsa around the Cincinnati area.', 'Mexican', '107 E 12th St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.6', '(513) 381-1596');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/8UvVLOXlZDkJeUfuBOLE5Q/348s.jpg', 'Nada', 'Reservations, Outdoor Seating, Seating, Television, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Free Wifi, Accepts Credit Cards, Table Service, Wine and Beer, Gift Cards Available', 'Mexican', '600 Walnut St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.4', '(513) 721-6232');
INSERT INTO restaurants(img, name, description,type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media3.fl.yelpcdn.com/bphoto/-AlgYmyXWcH9BlY9mpDPug/ms.jpg', 'Mita''s Restaurant', 'Mitas eclectic, farm-inspired menu focuses on both the traditional and modern foods and beverages of Spain and Latin America - with tapas, ceviches, cured hams, cheeses and large plates.  The wine program emphasizes Spain and the Old World.', 'Mexican', '501 Race St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.6', '(513) 421-6482');
INSERT INTO events(user_id, eventname, location, decisiondate, inviteurl)
	VALUES (1, 'Saturday Dinner', '45202', '2022-12-10 10:00:00', 'testURL');
COMMIT TRANSACTION;
