BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/D7hdCMvZQS7MscTghzr71A/348s.jpg','Rhinegeist Brewery', 'Brewing hoppy & sessionable craft beer and investing in the character of the Over the Rhine and greater brewing communities.', 'Brewery', '1910 Elm St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.5', '(513) 381-1356');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/tolQEd7e6F1bQmRXtYF_LQ/348s.jpg', 'Taft''s Ale House', '10+ brewed in house craft beers on tap, Tri-Tip Steak, Salads, Chicken, Salmon, all in the setting of a renovated old church that was built in 1850.', 'Brewery', '1429 Race St', 'Cincinnati', 'OH', '45202','11:00:00', '23:00:00', '4.5', '(513) 334-1393');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/crZJ8YPlUdckqj_el2HBUA/348s.jpg', 'BrewDog Cincinnati', 'Two hours south of our American HQ we opened an 8,500 sq ft craft beer mecca! With 24 taps of craft beer glory, a mezzanine chock full of games, and a beer school space for everything beer geekery, BrewDog Cincinnati is THE place to experience craft beer in The Queen City. We are also dog friendly in our outside areas, so you can bring your furry friend with you!', 'Brewery', '316 Reading Rd', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.0', '(513) 457-5287');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/X8PZHucus9wI6gP9ePwtQQ/348s.jpg', 'Braxton Brewing Cincinnati', 'Braxton Brewing Company melds the 500 year-old tradition of making beer with new age consumer technology. Located in Greater Cincinnati our Taproom of the Future will be a showcase to our craft beers, and redefine the beer drinking experience. We are creating the brewery of your dreams in the heart of the new Midwest, and cannot wait to pour you a pint!', 'Brewery', '331 E 13th St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.0', '(859) 261-5600');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/mKcWr3vj3_DexLBF6NXvuQ/348s.jpg','Samuel Adams Cincinnati Taproom', 'Located in the Over-The Rhine neighborhood, just a block away from historic Findlay Market, our Cincinnati Taproom features pints and flights of our innovative styles, rotating experimental beers, as well as fan-favorites like Samuel Adams Boston Lager, and seasonal brews like Samuel Adams Summer Ale.', 'Brewery', '1727 Logan St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.5', '(513) 412-3300');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/o5tVsT5Ye1OestY-we0OVQ/348s.jpg', 'Condado Tacos', 'We are all about the tacos, tequila + margaritas here at Condado Cincinnati Banks, but the main attraction is our build-your-own tacos! Choices range from toppings + proteins, to shells + sauces. We pride ourselves on having fresh ingredients made every single day and -- unlike other joints -- tacos made your way.', 'Mexican', '195 E Freedom Way', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.0', '(513) 263-1172');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/IAFd8m5KYNoxY-y7Xh9TCw/348s.jpg','Bakersfield', 'Serving up authentic, Mexican street fare, and a selection of over 100 tequilas and American whiskeys. Bakersfield is a spot where the food is simple, the service is warm and the atmosphere is alive.', 'Mexican', '1213 Vine St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.5', '(513) 579-0446');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://www.gomezsalsa.com/wp-content/uploads/2019/04/Location_OTR.jpg', 'Gomez Salsa', 'Gomez Salsa began in the small town of Brownsville, Texas where the best taco of my life was assembled by my abuelita (grandmother), Oralia Gomez. She also hand-chopped the most authentic salsa I’ve ever encountered, which my father made weekly for our family. From them, I learned to make salsa the way they did and began producing and selling Gomez Salsa around the Cincinnati area.', 'Mexican', '107 E 12th St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.6', '(513) 381-1596');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/8UvVLOXlZDkJeUfuBOLE5Q/348s.jpg', 'Nada', 'Reservations, Outdoor Seating, Seating, Television, Highchairs Available, Wheelchair Accessible, Serves Alcohol, Full Bar, Free Wifi, Accepts Credit Cards, Table Service, Wine and Beer, Gift Cards Available', 'Mexican', '600 Walnut St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.4', '(513) 721-6232');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
	VALUES ('https://s3-media3.fl.yelpcdn.com/bphoto/-AlgYmyXWcH9BlY9mpDPug/ms.jpg', 'Mita''s Restaurant', 'Mitas eclectic, farm-inspired menu focuses on both the traditional and modern foods and beverages of Spain and Latin America - with tapas, ceviches, cured hams, cheeses and large plates.  The wine program emphasizes Spain and the Old World.', 'Mexican', '501 Race St', 'Cincinnati', 'OH', '45202', '11:00:00', '23:00:00', '4.6', '(513) 421-6482');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/wso6sOaBxqDlJZOWtGKolQ/o.jpg', 'Hofbrauhaus Newport', 'Traditional bier brewed on site every day. An award-winning menu of German favorites and American classics. A vibrant environment modeled after the Munich original featuring live music and a beautiful biergarten.', 'Brewery', '200 E 3rd St', 'Newport', 'KY', '41071', '11:00:00', '23:00:00', '4.0', '(859) 491-7200');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/BMUY4k0bzzAazKHIu38PMQ/o.jpg', 'Wooden Cask Brewing Company', 'Wooden Cask Brewing Company is a modern microbrewery designed to honor traditional English pubs. Our 4000 square-foot taproom is home to a standard menu of 18 Wooden Cask beers, a rotating menu of small-batch brews, wines from our own winery, and an extensive bourbon selection. As a family-run business, we are proud to serve our Northern Kentucky community. Our taproom is fully renovated, and we offer private event space for personal and corporate use. Come enjoy our brews, grab a bite to eat, and relax with friends at Wooden Cask.', 'Brewery', '629 York St', 'Newport', 'KY', '41071', '11:00:00', '23:00:00', '4.5', '(859) 261-2172');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    VALUES ('https://cdn2.cincinnatimagazine.com/wp-content/uploads/sites/5/2016/03/CM_MAR16_TOP10_Mazunte.jpg', 'Mazunte Taqueria', 'Authentic street-style Mexican food. Tacos, enchiladas, toastadas, quesadillas, guacamole, queso, elote, margaritas. Vegetarian, vegan, and gluten-free friendly.', 'Mexican', '5207 Madison Rd Ste 100', 'Cincinnati', 'OH', '45227', '11:00:00', '23:00:00', '4.5', '(513) 785-0000');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/0VMoWjd9bZC7JDalZ0uJmg/o.jpg', 'Agave & Rye - Covington', 'We believe food is an adventure, taking you somewhere playful with every bite. We have made it our promise to deliver a chef inspired take on the standard taco. Elevating this simple food into something Epic. If you enjoy creative delicious food, and an endless selection of Bourbon, Tequila and Craft Cocktails, we promise Agave & Rye is the place for you.', 'Mexican', '635 Madison Ave', 'Covington', 'KY', '41011', '11:00:00', '23:00:00', '4.0', '(859) 360-1060');
INSERT INTO restaurants(img, name, description, type, address, city, state_abbrev, zip_code, open_time, close_time, rating, phone)
    VALUES ('https://s3-media0.fl.yelpcdn.com/bphoto/vKoQc0UJrhwea9b8jGJ9PA/o.jpg', 'MadTree Brewing', 'raft beer and excellent food from Catch-A-Fire Café. The large outdoor beer garden provide great space with an additional bar so you can soak in the outdoors and hang out with your pets. Boasts two private event spaces and venues for parties small to large.', 'Brewery', '3301 Madison Rd', 'Cincinnati', 'OH', '45209', '11:00:00', '23:00:00', '4.5', '(513) 836-8733');
INSERT INTO events(user_id, eventName, location, decisionDate, inviteCode)
	VALUES (1, 'Saturday Dinner', '45202', '2022-12-10 10:00:00', 'testURL');
COMMIT TRANSACTION;
